spring:
  application:
    name: kstream
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: http://localhost:8081
      bindings:
        organization:
          contentType: application/*+avro
          destination: organization-updates
          group: demokstream.org
          consumer:
            header-mode: raw
      kafka:
        streams:
          binder:
            brokers: localhost
            configuration:
              schema.registry.url: http://localhost:8081
              commit:
                interval:
                  mms: 1000
              default:
                key:
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                value:
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        bindings:
          organization:
            consumer:
              configuration:
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true
                key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
