spring:
  application:
    name: kstream
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: http://localhost:8081
      bindings:
        organization:
          contentType: application/*+avro
          destination: organization-updates
          group: demokstream.org
          consumer:
            header-mode: raw
        pcin:
          consumer:
            header-mode: raw
            user-native-encoding: true
          content-type: application/json
          destination: pcs
          group: pcs
        pcout:
          destination: pcs
          producer:
            user-native-encoding: true
        pvin:
          consumer:
            header-mode: raw
          destination: pvs
        pvout:
          destination: pvs
          producer:
            header-mode: raw
      kafka:
        streams:
          binder:
            brokers: localhost
            configuration:
              commit:
                interval:
                  mms: 1000
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  #serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        bindings:
          organization:
            consumer:
              configuration:
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true
                key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
